language: python
dist: xenial
sudo: required
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
install:
  - python3 -m pip install tox
script:
  - tox
